### ISSUE TITLE
Gensim warning on word_similarity_explorer_gensim()

### ISSUE THREAD

**Issue by David-Herman** [JasonKessler/scattertext#14]
Hello,

I am getting the following error with scattertext on Python 2.7
   
    WARNING:gensim.models.word2vec:supplied example count (67681) did not equal expected count (135362000)

In the word_similarity_explorer() without gensim I can pass along the nlp object I get from the following command.
      
    nlp = en_core_web_md.load()

The output overall looks correct but I am wondering if the error is related to the nlp model. My code is comparable to the example code in the readme.

**Comment by JasonKessler** [comment]
I'm just focusing on maintaining the project in Python 3, since I lack the resources for parallel Python 2 implementation.  Running the Gensim sample code in Py3 results in no warnings on my end.

Do let me know if this appears in Py3 and precise instructions on how to recreate it.

If you'd like, feel free to poke around the code and see if you can figure out what's happening.

**Comment by David-Herman** [comment]
ok, I will try to replicate the error in py3. My guess was that the warning had to do with lack of a symbolic link in the spacy model data folder due to lack of admin rights on this machine and me importing via the above command. You can close the ticket until I can replicate the issue.
